name: Release Patch Version

on:
  workflow_dispatch:

jobs:
  build: 
    uses: thomas-ttd/SharedWorkflows/.github/workflows/shared-release.yaml@main
    with:
      type: 'Patch'
    secrets: inherit
