name: Release Patch Version

on:
  workflow_dispatch:

jobs:
  build: 
    uses: thomasm-ttd/SharedWorkflows/.github/workflows/shared-release.yaml@main
    with:
      release_type: 'Patch'
    secrets: inherit
