name: Release Major Version

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Minor Version
        run: |
          old_ver=$(jq '.version' version.json | tr -d '"')
          new_ver=$(echo $old_ver | cut -d'.' -f 1)
          new_ver=$(echo $new_ver.0)
          new_ver=\"$new_ver\"
          echo $(jq ".version=$new_ver" version.json) > version.json

      - name: Set Version
        uses: dotnet/nbgv@master
        with:
          setAllVars: true
      
      - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
      - run: env

      - name: Update pom.xml
        id: version
        run: |
          current_version=$(grep -o '<version>.*</version>' pom.xml | head -1 | sed 's/<version>\(.*\)<\/version>/\1/')
          new_version="$NBGV_SimpleVersion-$NBGV_GitCommitIdShort"
          sed -i "s/$current_version/$new_version/g" pom.xml
          echo "Version number updated from $current_version to $new_version"
          echo "::set-output name=new_ver::$new_version"

      - name: Build and Run Unit Tests
        run: mvn -B clean compile test

      - name: Commit Pom.xml and version.json
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml version.json'
          author_name: Release Workflow
          author_email: unifiedid-admin+release@thetradedesk.com
          message: 'Updated version to ${{ steps.version.outputs.new_ver }}'

